services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    environment:
      - VITE_HOST=0.0.0.0
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: /usr/src/app/src
        - action: rebuild
          path: ./client/package.json
          target: /usr/src/app/package.json
    volumes:
      - ./client/package.json:/usr/src/app/package.json
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    env_file:
      - ./server/.env
    develop:
      watch:
        - action: sync
          path: ./server/src
          target: /usr/src/app/src
        - action: rebuild
          path: ./server/package.json
          target: /usr/src/app/package.json
    volumes:
      - ./server/migrations:/usr/src/app/migrations
      - ./server/package.json:/usr/src/app/package.json
    depends_on:
      - db
      - mailtrap

  db:
    container_name: devcanvas-db-1
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devcanvas
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: devcanvas-pgadmin-1
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  mailtrap:
    container_name: devcanvas-mailtrap-1
    image: eaudeweb/mailtrap
    ports:
      - "1080:80"   # Interface web : identifiant et mot de passe => mailtrap
      - "1025:25"   # SMTP

volumes:
  db_data:
  pgadmin_data:
