# ========================================================================
# WORKFLOW: Vérification de la qualité du code et tests
# ========================================================================
# Ce workflow:
# 1. Vérifie le formatage du code (client et serveur)
# 2. Vérifie le linting du code (client et serveur)
# ========================================================================

name: Code Quality Check

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  quality-check:
    name: Format and Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Installation des dépendances
      - name: Install dependencies
        run: |
          npm ci
          cd client && npm ci
          cd ../server && npm ci

      # Vérification du formatage
      - name: Check formatting
        run: npm run format:check

      # Vérification du linting
      - name: Run linting
        run: npm run lint